### ISSUE TITLE
Paladin knight's vow pledge changes

### ISSUE THREAD

**Issue by FoskSnake** [chadvandy/cbfm_wh3#1087] opened 2023-06-09 23:06 UTC
**Describe the bug**
After recruiting a paladin hero and pledging to chivalry for the knights vow, it changes on it's own to the pledge to order.

**Expected behavior**
Once a pledge is selected, should stay that way.

**To Reproduce**
1. Playing as Alberic de Bordeleaux
2. Recruit a paladin
3. Choose pledge to chivalry
4. Play a battle
5. Pass the turn

**Screenshots**

![Pledge to chivalry](https://github.com/chadvandy/cbfm_wh3/assets/136131106/1d516984-c67f-4de3-9a6c-aea9d55498ac)
![Pledge to order](https://github.com/chadvandy/cbfm_wh3/assets/136131106/68ed729c-c2bf-403b-ab6f-9f71d4125947)

**Additional Info**

Using the following mods:
Community Bug Fix Mod - 3-Batch 3
Victory Conditions Overhaul
Auto Resolve Quest Battles
One Button Respec

**Comment by Harmandodelavega** [comment] 2023-06-09 23:25
we updated like 90 minutes ago, did this happen before?

**Comment by FoskSnake** [comment] 2023-06-10 05:20
Think so, took me a while to post it because i wanted to check if it was a bug or just me

**Comment by mfvreeland** [comment] 2023-06-10 13:51
This was 100% fixed in our last update (it was also caused by us previously; sorry about that). If it's still occurring for you, make sure your workshop files have updated. Steam is very inconsistent about this.

**Closed by mfvreeland** 2023-06-10 13:51 UTC
Labels: unvalidated

**Comment by FoskSnake** [comment] 2023-06-10 13:55
Thought so, was just testing it, anad being unable to reproduce it on vanilla or after updating the mod.
