### ISSUE TITLE
Rebirth miscast deals no damage when it fails, so it will eventually always succeed

### ISSUE THREAD

**Issue by Cataph** [chadvandy/cbfm_wh3#137] opened 2022-09-05 14:35 UTC
`When doing the battle for Gordinar the flame dragon as Imrik, the dragon's phoenix rebirth ability triggers every time instead of 50% of the time. (It happened 11 times before I lost due to unkillable Gordinar) The chances that this happened naturally looks like 1/2048.`

This is wh2_main_unit_passive_rebirth, the same exact passive used by the fire phoenix. Don't see anything wrong at all in the tables, and the 50% miscast can't be affected by other abilities.

**Comment by Harmandodelavega** [comment] 2022-10-30 19:42
2 things: @Cataph 
1:Does this thing not have a healing cap? 
2:Rebirth miscast does no damage (projectile_explosions)

**Comment by Cataph** [comment] 2022-10-30 20:26
1. definitely should, but with the huge hp pool of a boss it still means it's 75% more hp of a lot.
2. oh that explains it. do mind that last time I checked it's still the same ability as the red phoenixes so those are always rebirthing too.

**Comment by Harmandodelavega** [comment] 2022-10-31 19:52
@Cataph aren't all heal effects hp percent now?

**Comment by Harmandodelavega** [comment] 2022-10-31 19:56
Trying to understand if this thing has a busted healing cap or not

**Comment by mfvreeland** [comment] 2022-11-16 14:27
Is this still a bug? It seems like a pretty big deal.

**Comment by Harmandodelavega** [comment] 2022-11-16 14:51
yep, the rebirth thing in the tables at least does 0 dmg

**Comment by mfvreeland** [comment] 2022-11-24 11:43
Looking into the tables a little deeper on this, it appears that the miscast projectile itself never did direct damage, but the effect should trigger a special ability phase `wh2_main_unit_passive_rebirth_miscast` that deals 6650 damage five times over one second. In WH2, it worked similarly, although the damage/frequency numbers were a bit different (1248 damage five times over half a second).

I think we need to verify this bug is still happening.

**Comment by mfvreeland** [comment] 2022-11-24 14:01
I've tested this in custom battle in 2.3, and it appears that rebirth is working normally. In 10 trials using a fire phoenix, I got a solid 50/50 spread of insta-death vs. respawn. Closing as not a bug (anymore, anyway).

**Closed by mfvreeland** 2022-11-24 14:01 UTC
Labels: not-a-bug
