### ISSUE TITLE
Gotrek lacks Mentor skill

### ISSUE THREAD

**Issue by SubRyan** [chadvandy/cbfm_wh3#1868] opened 2024-06-16 05:01 UTC
**Describe the bug**
Gotrek lacks Mentor skill since the release of the new skill tree

**Expected behavior**
Gotrek should have the Mentor skill like the other Dragon Slayer heroes

**To Reproduce**
1. Play as Dwarfs or Empire
2. Recruit Gotrek
3. Notice lack of Mentor skill

**Screenshots**

![image](https://github.com/chadvandy/cbfm_wh3/assets/13555076/9d3ac02c-8c8c-46c2-a231-408e174ddd1d)

**Saves**

**Additional context**
I believe this to be an oversight as other Legendary Heroes have had the Mentor skill added to them. The Dragon Slayer LH Garagrim Ironfist has the Mentor skill

**Comment by mfvreeland** [comment] 2024-06-16 13:23
Duplicate of #1869

**Closed by mfvreeland** 2024-06-16 13:23 UTC
Labels: duplicate
