### ISSUE TITLE
Plagues generated through cults don't count towards Epidemius' tally 

### ISSUE THREAD

**Issue by Balian248** [chadvandy/cbfm_wh3#1953] opened 2024-09-05 06:32 UTC
This is a copy of a report on the total war forums. https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/4085?page=1

"Playing as Epidemius I noticed that despite generating many plagues through the cult building that generates them in own and adjacent provinces the Plague tally doesn't increase. It seems that plagues generated through cults don't count towards the tally."  

Start an Epidemius campaign

Create a cult

Build the Cult Magus building and create a Cult Magus

Create an advance Cult through the Cult Magus

Build the Ritual of Pestilence building that generates Plagues in and around the settlement

Press end turn

Notice that while, plagues were generated the tally didn't go up.

![20240901184907_1__2_-2](https://github.com/user-attachments/assets/0aac04c5-ab2a-4a88-a012-ebd4745e174d)

**Comment by mfvreeland** [comment] 2024-09-13 14:56
Duplicate of #1875

**Closed by mfvreeland** 2024-09-13 14:56 UTC
Labels: unvalidated
