### ISSUE TITLE
Boon of Chaos "Attuned to Chamon/Uigu/Shyish" does not unlock on heroes

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/cbfm_wh3#602] opened 2022-11-15 16:00 UTC
does not trigger unless it's a lord

**Comment by mfvreeland** [comment] 2024-03-15 16:41
Seems they account for embedded heroes since altering the script to account for the new Tzeentch Exalted Hero, but I haven't tested it.

**Comment by mfvreeland** [comment] 2024-05-16 19:50
Confirmed fixed in my current campaign

**Closed by mfvreeland** 2024-05-16 19:50 UTC
Labels: unvalidated, maybe-patched
