### ISSUE TITLE
Stag Knight rank 7 skill not working

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#555] opened 2022-11-06 09:23 UTC
**Describe the bug**
At least some of Orion (wood elf lords) red line skills for rank7 units seem to not be working.
Noticed on the Swift & Sturdy & Great stag knights skill as shown in screenshots.

**Expected behavior**
Red line skills affecting rank7+ units normally

**To Reproduce**
1. Play as Wood elf (orion in screenshots)
2. Level units to golden ranks (great stag knights in screenshot)
3. Notice the red line rank7 skills are not applying (swift & sturdy skill in screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/55892027/200163162-4b3354f2-02b1-4aaf-9e76-6280f0751d28.png)

**Additional context**
Many of these rank7 skills not working is an ancient issue from TWW2.
Would not be surprised if there are several more such bugged skills across all factions.
Original reddit thread about this issue mentions Festus also having similar bugs
 https://www.reddit.com/r/totalwar/comments/yn2zs5/orion_red_line_bugged/

**Comment by mfvreeland** [comment] 2022-11-24 14:36
Is is only Great Stag Knights where this isn't being applied? It's probably just another unit set issue, but I want to make sure we only fix each of these once.

**Comment by mfvreeland** [comment] 2023-06-23 13:35
Duplicate of #929 (this one actually came first, so cheers @Bogdanov89, sorry we missed it)

**Comment by mfvreeland** [comment] 2023-06-23 19:18
@Harmandodelavega My bad, didn't read carefully enough. It looks like this one was fixed by CA anyway, though. Great Stags are correctly affected in 3.1.

**Closed by mfvreeland** 2023-06-23 19:18 UTC
Labels: unvalidated
