### ISSUE TITLE
!!! MISSING TANKS FIRING SOUND !!!

### ISSUE THREAD

**Issue by sirmicou** [chadvandy/cbfm_wh3#893] opened 2023-03-27 16:39 UTC
Hello guys,

When Empire steam tanks are firing (with the main canon, not turret), there is no sound...

Is it possible to fix that please ?

Thank you !

**Comment by mfvreeland** [comment] 2023-03-28 20:23
Duplicate of #248

**Closed by mfvreeland** 2023-03-28 20:23 UTC
Labels: unvalidated
