### ISSUE TITLE
Inferno Slugs for Ezar Doombolt

### ISSUE THREAD

**Issue by AlarielleRadiant** [chadvandy/cbfm_wh3#2166] opened 2024-12-31 04:28 UTC
Inferno Slugs for Ezar Doombolt may not help much.
![20241231122411_1](https://github.com/user-attachments/assets/fa1ec89b-13db-445d-8ee3-cd2dc136df33)
![20241231122447_1](https://github.com/user-attachments/assets/e36d075e-15cf-4294-89ba-6c32f3658223)

**Comment by mfvreeland** [comment] 2024-12-31 14:37
Duplicate of #1728, still needs verification.

**Closed** 2024-12-31 14:37 UTC
Labels: duplicate

**Comment by AlarielleRadiant** [comment] 2025-01-11 15:59
There's no doubt that the skill template of Inferno Castellan was mechanically applied to Ezar Doombolt. It causes 3 bugs thus.

1. "Inferno Slugs" will change the special bullets of Ezar Doombolt, the same as Inferno Castellan
2. Sundering attacks by "Motlen Cores" will cover poison attacks by Ezar Doombolt.
3. "Inspiring Inferno" in Infernal Castellan only affects Infernal Guard (Fireglaives) unit now, just like I said before.   
#1911
[https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/3079-inspiring-inferno?page=1](url)
