### ISSUE TITLE
The Druzhina's Speaks to the Forest skill grants Regeneration to the whole army

### ISSUE THREAD

**Issue by Autumnchain** [chadvandy/cbfm_wh3#1439] opened 2024-02-25 15:41 UTC
Documented here: https://www.youtube.com/watch?v=w0Jl06GDWzg

**Comment by Drazhir2** [comment] 2024-02-25 16:11
duplicate of https://github.com/chadvandy/cbfm_wh3/issues/1428 which is already fixed

**Closed by Drazhir2** 2024-02-25 16:11 UTC
Labels: unvalidated
