### ISSUE TITLE
Drycha quest does not reward Stolen Power trait (Buttermilk)

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#74] opened 2022-09-02 18:38 UTC
https://steamcommunity.com/sharedfiles/filedetails/?id=2862206026&searchtext=
https://forums.totalwar.com/discussion/318393/bug-drychas-quest-battle-to-gain-coeddil-did-not-work

**Comment by mfvreeland** [comment] 2022-11-16 14:19
Assuming this just needs the Steam fix implemented?

**Comment by Harmandodelavega** [comment] 2022-11-16 14:49
the guy said he didn't test in 2.2 but should work

**Comment by Harmandodelavega** [comment] 2022-11-23 11:31
@mfvreeland did you test this? if not needs label

**Comment by mfvreeland** [comment] 2022-11-23 13:58
@Harmandodelavega Not in 2.3, where it is probably unnecessary because CA apparently fixed the underlying issues with the quest battle itself. If anyone can confirm the quest (and rewards) work in vanilla, I will remove this change before merge.

**Comment by mfvreeland** [comment] 2022-11-23 17:43
My understanding is that the whole reason the linked mod existed was because the ordinary quest rewards were broken thanks to the quest itself being broken. Fixing the quest objectives should fix the quest and thus the rewards (in theory, anyway).

**Comment by mfvreeland** [comment] 2022-11-24 11:23
According to [forum reports](https://forums.totalwar.com/discussion/318393/bug-drychas-quest-battle-to-gain-coeddil-did-not-work), the Coeddill spawning problem has been fixed, anyway. I am awaiting confirmation on Drycha's unique trait.

**Comment by Harmandodelavega** [comment] 2022-11-24 12:30
Sorry to dump another thing on you but there's this too https://trello.com/c/NjsvwYw8/212-ai-drycha-doesnt-get-the-potion-of-sacre-trait , don't know if even the player gets that trait now

**Comment by mfvreeland** [comment] 2023-11-20 19:19
Possibly fixed in 4.1:

"Fixed an issue where the Wood Elf forest settlement chain was not providing the correct number of construction slots at each level."

**Comment by mfvreeland** [comment] 2023-11-21 19:50
Confirmed fixed in 4.1.

**Comment by floskan** [comment] 2024-03-05 22:53
Not working anymore

**Closed** 2024-03-07 22:14 UTC
Labels: resolved

**Comment by mfvreeland** [comment] 2024-03-12 16:04
So we re-fixed this? Nice.

**Comment by floskan** [comment] 2024-03-12 16:35
We've come full circle

**Comment by mfvreeland** [comment] 2024-03-19 12:53
... and maybe back again (4.2.2): "Fixed Drycha not receiving the "Stolen Power" trait when unlocking Coeddil"

**Comment by floskan** [comment] 2024-04-09 12:08
It's fixed completely now but hef tree spirits get's double taps of this buffs. Not that i think it's likely at all that Drycha will ever end up with hef tree spirits in her army
