### ISSUE TITLE
Incorrect stats for Grudge Settler Grudge Thrower and Flame Cannon for Dwarfs

### ISSUE THREAD

**Issue by Jtheos** [chadvandy/cbfm_wh3#1898] opened 2024-07-02 15:08 UTC
It appears as though the range is for both these artillery units is incorrect and I believe the damage is incorrect for the flame cannons as well.

I believe the range should be 440 for the Grudge Throwers and 250 for the Flame Cannons and the damage should be around 650 for the Flame Cannons although I'm not 100% sure.

1. Enter a campaign battle or custom battle as the Dwarfs.
2. Have a unit of Grudge Settler Flame Cannons and Grudge Throwers in your army.
3. Hover over the unit stats to see.
4. 
![11](https://github.com/chadvandy/cbfm_wh3/assets/174260701/e343d031-ad0b-445d-8f9f-3a90bc96721b)
![22](https://github.com/chadvandy/cbfm_wh3/assets/174260701/f05998e1-b971-4a84-b891-06f932bd7745)

**Comment by mfvreeland** [comment] 2024-07-02 15:30
It's erroneously showing info from the shrapnel (secondary) projectile instead of the primary.

Duplicate of #1897

**Closed by mfvreeland** 2024-07-02 15:30 UTC
Labels: duplicate
