### ISSUE TITLE
Clan Angrund The Greatest of Grudges missing reward

### ISSUE THREAD

**Issue by TheTiberon** [chadvandy/cbfm_wh3#366] opened 2022-09-20 18:30 UTC
**Describe the bug**
Clan Angrund grudge to retake Karak Eight Peaks (The Greatest of Grudges) does not have a reward as originally intended.

**Expected behavior**
There was a reward associated to the grudge in Warhammer 2 at one point and it exists in the db tables in wh3. During one of the patches in wh2 they broke the associating between grudge and reward and hadn't fixed it.

**To Reproduce**
1. Start a new game as Belegar Ironhammer/Clan Angrund.

**Additional context**
Found the fix in the attached .pack works. Tested in a couple campaigns with no issues. 

It requires one entry into "cdir_events_mission_payloads_tables" that points the "Mission Key" for the grudge to the correct "Value" for the rewards that were originally associated to it.
[Oath_Fulfilled.zip](https://github.com/chadvandy/cbfm_wh3/files/9610354/Oath_Fulfilled.zip)

**Comment by mfvreeland** [comment] 2022-09-21 03:33
Duplicate of #176, fixed in #254

**Closed by mfvreeland** 2022-09-21 03:33 UTC
Labels: duplicate
