### ISSUE TITLE
Alith Anar (High Elves) upkeep trait bugged

### ISSUE THREAD

**Issue by Stormymilk** [chadvandy/cbfm_wh3#302] opened 2022-09-14 09:07 UTC
One of Alith Anar's campaign effects is:
"Upkeep: -50% for Shadow-walkers and Shadow Warriors units"
![image](https://user-images.githubusercontent.com/113509274/190109240-12a3081a-4ac3-4c0a-87b1-e3587e104990.png)

Shadow-walkers are receiving the upkeep reduction (from 275 to the current 138), but Shadow Warriors aren't - Shadow Warriors upkeep should be ~107, rather than the current 213.
![image](https://user-images.githubusercontent.com/113509274/190108775-b7ef09d4-8fe2-486f-9d2f-ea897b18c927.png)

No exceptional requirements to reproduce, just build the Aesanar Camp in his starting capital, this can be done from turn 2 - it happens 100% of the time, and has been replicated in the Total War forums, and Reddit.

No mods used. Full screenshot:
![image](https://user-images.githubusercontent.com/113509274/190111419-090275d9-39d0-4b2b-b415-734a2db76be9.png)

**Comment by mfvreeland** [comment] 2022-09-14 18:30
Duplicate of #112, fixed and merged in #238

**Closed** 2022-09-14 22:58 UTC
Labels: duplicate
