### ISSUE TITLE
Nurgle Beasts not buffed by Daemonic melee red line

### ISSUE THREAD

**Issue by Velykos** [chadvandy/cbfm_wh3#148] opened 2022-09-06 16:24 UTC
Not sure if this applies to any other Daemonic monsters but the red line says DAEMONIC and MELEE
Doesn't specify Infantry
So the red line should buff Beasts, but it doesn't

**Comment by floskan** [comment] 2022-09-06 17:06
Duplicate of #15

**Closed** 2022-09-06 18:49 UTC
