### ISSUE TITLE
Tor Elyr´s special landmark (Royal Ellyrian Stables) missing

### ISSUE THREAD

**Issue by AdrianKarrantza** [chadvandy/cbfm_wh3#294] opened 2022-09-13 21:46 UTC
**Describe the bug**
Once you own Tor Elyr as Avelorn (High Elf faction), there is no option to build the city´s special landmark.

**Expected behavior**
There should be an available special landmark for any High Elf faction (Royal Ellyrian Stables).

**To Reproduce**
1. Play as Avelorn
2. Attack region TOR ELYR (or get it via confederation)
3. Select a building slot.
4. Missing landmark (Royal Ellyrian Stables). 

**Screenshots**

**Saves**

**Additional context**

**Comment by mfvreeland** [comment] 2022-09-13 22:19
Duplicate of #195

**Closed** 2022-09-14 00:21 UTC
Labels: duplicate, unvalidated
