### ISSUE TITLE
Nuln tier 2 landmark loses recruitment of tier 1 units

### ISSUE THREAD

**Issue by IMRZ** [chadvandy/cbfm_wh3#404] opened 2022-09-24 12:58 UTC
**Describe the bug**
The Nuln special landmark buildings only allows the recruitment of a single artillery unit. In WH2 the special landmark buildings allowed the recruitment of many more artillery units. See screenshots.

**Screenshots**
WH2:
![image](https://user-images.githubusercontent.com/1845806/192098769-2bb6281c-e9da-4529-b6e5-443c6082cfb7.png)

WH3: 
![image](https://user-images.githubusercontent.com/1845806/192098259-4a961844-8cb6-4f65-8efd-c822dee55f78.png)

**Comment by mfvreeland** [comment] 2022-11-22 18:14
Looks like this may have been fixed in 2.3, based on a quick look at the diff. Needs confirmation.

**Comment by Harmandodelavega** [comment] 2022-11-22 19:02
lol they broke it more, gave tier 3 more units than tier 5

**Comment by mfvreeland** [comment] 2022-11-23 19:22
Looks like those changes could be intentional. Not enough info to conclude they aren't, anyway.

**Comment by Harmandodelavega** [comment] 2022-11-23 21:23
Don't think I've ever seen a building get weaker when you upgrade it

**Comment by IMRZ** [comment] 2022-11-23 21:48
Looks like they tried to buff it by adding handgunners and moving mortar warwagons to tier 3. But forgot to add the tier 3 building units to the tier 5 building. I will try submit a patch tomorrow.

**Comment by mfvreeland** [comment] 2022-11-23 22:36
Oh, I see. I was looking at the changes in the DB and made the same mistake. Honestly, I don't know why they don't just change it so that later bindings in a given chain always include the recruitable units from previous buildings by default, but I agree it looks like they just forgot to account for that.

**Closed** 2022-11-25 00:52 UTC
Labels: resolved, not-fixed-in-2.3

**Comment by mfvreeland** [comment] 2023-04-15 18:13
Reported fixed in 3.0, needs verification.

**Comment by mfvreeland** [comment] 2023-04-16 13:31
Confirmed fixed by CA in 3.0, removing from CBFM.
