### ISSUE TITLE
Skarbrand faction does not replenish in regions not razed recently by him or razed by others

### ISSUE THREAD

**Issue by Bogdanov89** [chadvandy/cbfm_wh3#88] opened 2022-09-03 12:13 UTC
Skarbrands armies are unable to replenish in already ruined regions because "army is in foreign territory".
But his faction unique benefit is "Armies replenish in foreign territories".
This is a bit odd because the replenishment works if skarbrand razes the city thus turning the region into a ruin, but if he simply walks into an already ruined region he will not replenish regardless of army stance.

![image](https://user-images.githubusercontent.com/55892027/188269930-e97f16d4-c9ca-4e3e-ab58-017ad9184e7b.png)

**Comment by CRUNKULON** [comment] 2022-09-04 10:44
This also seems to apply to the Warriors of Chaos Dark Gift Deadly Transmission.

**Comment by mfvreeland** [comment] 2022-11-16 14:21
Not sure this can be fixed by us. Is this replenishment behavior table-defined?

**Comment by Bogdanov89** [comment] 2023-07-19 12:33
@mfvreeland  Hey sorry to tag, just to mention that this issue is still present in 3.1
Reproducible easily at just turn 3 , i sacked the nearby city Sunken Kernarch and entered "encamp stance".
However my Skarbrand army could not replenish because of "army is in foreign territory".
Needless to say this completely bricks Skarbrands campaign since he must replenish & keep moving otherwise he goes bankrupt.
![image](https://github.com/chadvandy/cbfm_wh3/assets/55892027/d656c1a3-7642-4450-872b-048c6e744b77)

**Comment by Bogdanov89** [comment] 2023-07-19 12:39
And here it is not working even when in a "ruined" region that my Skarbrand razed a turn ago (summoned a blood host as post battle option)

![image](https://github.com/chadvandy/cbfm_wh3/assets/55892027/9a53deb5-b80e-4fef-a27b-0d0ff971da7a)

**Comment by Bogdanov89** [comment] 2023-07-22 07:25
After a bit of investigation by CA and some other folks at Tww3 forums it seems that everyones favorite beastmen lord Malagor is to blame for this.

He has a (new?) trait where he prevents replenishment of local armies by 100% in the province that he is located in.
Problem is that he is often invisible (army stance) and can easily teleport around, making his presence extremely random.
Furthermore it could be that his trait works only against factions he is at war with - and not every Skarbrand campaign makes an enemy out of Malagor.
And furthermore the UI tooltip/description & army status makes absolutely no mention of this "debuff" being inflicted upon the army from Malagor being in the same province.

So i believe that all these Skarbrand replenishment issues could be explained by going to war with Malagor after which he will teleport around & stay invisible, randomly preventing replenishment in huge swaths of land without any textual explanation.

The only "fix" here that could perhaps be worth considering is making it clear to the player via UI that his armies are not replenishing because of Malagor being somewhere in the province.
Since the current tooltip of "not replenishing due to being in foreign territory" is flat out wrong and deceiving, especially for Skarbrand faction.

**Comment by floskan** [comment] 2023-07-22 12:19
> After a bit of investigation by CA and some other folks at Tww3 forums it seems that everyones favorite beastmen lord Malagor is to blame for this.
> 
> He has a (new?) trait where he prevents replenishment of local armies by 100% in the province that he is located in. Problem is that he is often invisible (army stance) and can easily teleport around, making his presence extremely random. Furthermore it could be that his trait works only against factions he is at war with - and not every Skarbrand campaign makes an enemy out of Malagor. And furthermore the UI tooltip/description & army status makes absolutely no mention of this "debuff" being inflicted upon the army from Malagor being in the same province.
> 
> So i believe that all these Skarbrand replenishment issues could be explained by going to war with Malagor after which he will teleport around & stay invisible, randomly preventing replenishment in huge swaths of land without any textual explanation.
> 
> The only "fix" here that could perhaps be worth considering is making it clear to the player via UI that his armies are not replenishing because of invisible Malagor being somewhere in the province. Since the current tooltip of "not replenishing due to being in foreign territory" is flat out wrong and deceiving, especially for Skarbrand faction.

The takeaway here is that it's not a bug

**Closed by floskan** 2023-07-22 12:19 UTC
Labels: not-a-bug
