### ISSUE TITLE
Inspiring Inferno only applying to infernal guards (fireglaives)

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2060] opened 2024-12-15 13:00 UTC
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5562-inspiring-inferno-still-not-fixed?page=1

**Comment by mfvreeland** [comment] 2024-12-19 19:34
Duplicate of #1911

**Closed by mfvreeland** 2024-12-19 19:34 UTC
Labels: duplicate
