### ISSUE TITLE
Only Skarsnik shows his specific Waaagh pop up description when hovering over Greenskin faction's specific Waaaghs

### ISSUE THREAD

**Issue by TotalWarhead** [chadvandy/cbfm_wh3#835] opened 2023-01-03 01:41 UTC
For all of the other Greenskin factions, the generic Waaagh pop-up appears

**Comment by mfvreeland** [comment] 2023-01-04 22:40
Duplicate of #468

**Closed by mfvreeland** 2023-01-04 22:40 UTC
Labels: duplicate
