### ISSUE TITLE
Thorek and Runelords use the wrong animations (+Awsomnerd/Mandras)

### ISSUE THREAD

**Issue by Awsomnerd** [chadvandy/cbfm_wh3#1163] opened 2023-06-27 01:17 UTC
#867
Thorek Ironbrow and Runelords use Thorgrims unarmed anvil animations, instead of their own uniqe ones given to them in game 2. Some of their vfx are missing as well.
 
I have already made a mod that fixes these issues called Thorek Animation and Floating Anvil Fix here, https://steamcommunity.com/sharedfiles/filedetails/?id=2945364561

Play as Runelords or Thorek in wh2 to notice they had animations where they strike their anvils and lighting spreads across the ground for all their attacks and charges. Then play game 3 and you'll see they are using Thorgrims anvil animation instead, as well as vfx missing from their hammers.

They are really cool animations and deserve to be in the game I've reported it everwhere I could report, but it has yet to be acknowledged by CA so far.

**Comment by floskan** [comment] 2024-02-27 21:54
We got permission to use this. But while this works for changing Thoreks animation back to his original one, his spellcast animation stops working instead. Would you have any ideas as to why @mfvreeland ? I just grabbed the pack from the workshop.

**Comment by Harmandodelavega** [comment] 2024-02-27 22:05
check out #867 I kept both of them just in case

**Comment by floskan** [comment] 2024-05-11 09:59
"Hey I was just checking out the CBFM mod with the Thorek animations fix now in it, and I don't think the animations were added to him correctly. Thorek should be holding his hand much further up the shaft of the hammer so when he stikes the anvil it doesnt hang over. As it is in CBFM he missis the anvil when he striks it. If all the correct animations are assigned to him it will also change the placement of his hand, to the correct position.  So I think there must be some missing animations, (maybe the idle animations), and/or he could still have some of Thorgrims animations that need to be removed. I didn't see the spell animations working either."  Got this message from the awsomnerd, I admittedly haven't tried Thorek in a long while but there might be a chance something changed with the game itself because the animations all worked fine when I tested this.

**Comment by mfvreeland** [comment] 2024-05-12 05:07
I just tested it, and the only difference I can see between Awesomnerd's version and ours (which is essentially just a lightly modified version of his) is that the casting animation works in ours. The combat animations look exactly the same to me. Someone else should check to be sure, but maybe there was a mod conflict or something.

**Comment by floskan** [comment] 2024-05-12 16:45
I can check when i get the time. He mentioned this as well: 
![Skärmbild 2024-05-12 184458](https://github.com/chadvandy/cbfm_wh3/assets/34427023/f6ec041e-7127-4b2f-a945-a257549aa536)

**Comment by mfvreeland** [comment] 2024-05-12 21:14
I can confirm that the hand positioning is different, although imo this is less noticeable than the lack of spellcasting animations. I will investigate further when I have time and report back.

**Comment by mfvreeland** [comment] 2024-05-13 02:10
We had a different animation reference in our version for the position of the right hand equipment, which translated into the wrong hammer position as Awesomnerd pointed out. All of the other animations were right, but the hammer position was slightly off. This has now been fixed in main, and I also got rid of the animation fragment file from Awesomnerd's fix, as it's a holdover from the WH2 animation system and doesn't actually do anything in WH3.

Our version still preserves the casting animations, and because we are overwriting the vanilla animation set rather than creating a new one, we don't need any additional DB changes like Awesomnerd's mod has (side note: he is using an outdated land_units table, which is messing with Thorek and the Runelord's attributes -- we may want to tell him).

**Closed** 2024-05-13 02:10 UTC
Labels: resolved

**Comment by floskan** [comment] 2024-05-13 09:11
Nice job 👌

**Comment by Drazhir2** [comment] 2024-06-04 14:44
did they? :)

![image](https://github.com/chadvandy/cbfm_wh3/assets/135981276/cc342d25-0ecf-4cb2-89fc-faa914f2b197)

**Comment by floskan** [comment] 2024-06-25 09:04
Maybe patched still applies here since "Added missing VFX and audio to Thorek's Anvil of Doom melee attacks, including a fresh new effect where his anvil runes glow brighter when making a strike!" and "Resolved an issue preventing Anvil of Doom characters from performing melee attacks under certain circumstances"

**Comment by mfvreeland** [comment] 2024-06-26 16:45
CA mostly fixed this. Thorek/Runelord still don't have a working casting animation when not on the Anvil of Doom, though, so I'll keep that part of our fix.
