### ISSUE TITLE
Manticores benefitting from wrong 7+ red line

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#146] opened 2022-09-06 08:03 UTC
Not sure this qualifies as a bug but manticores is under freakish mutations (monsters and war beasts) and not under speed & malice (cavalry and flying units) daemonic fliers is under speed and malice. I don't really know how to move units between buffs without them catching both

**Comment by Bogdanov89** [comment] 2022-09-06 16:59
Lore-wise Manticores belong under something called "freakish mutations" so perhaps it was intended since they are more of a flying brute and less of a graceful fragile cavalry?
I really do not know how to tell what CA intended here.

**Comment by Harmandodelavega** [comment] 2022-09-14 19:58
Technically they are both a war beast and a flying unit so we'll just close this one

**Comment by Harmandodelavega** [comment] 2022-10-02 01:14
ok, maybe it's a bug

**Comment by mfvreeland** [comment] 2023-05-27 19:18
No consensus on whether or not this should be fixed.

**Closed by mfvreeland** 2023-05-27 19:18 UTC
Labels: opinion/discuss
