### ISSUE TITLE
Chosen and Chaos Warriors of Khorne units have no visual flame effect on their weapons 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2092] opened 2024-12-17 21:04 UTC
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5674-update-6-0-0-chosen-and-chaos-warriors-of-khorne-units-have-no-visual-flame-effect-on-their-weapons?page=1

**Comment by mfvreeland** [comment] 2024-12-19 22:22
Duplicate of #2091

**Closed by mfvreeland** 2024-12-19 22:22 UTC
Labels: duplicate
