### ISSUE TITLE
CHAOS LORD OR EXALTED HERO WITH CHAOS CHARIOT OR GORBEAST CHARIOT 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2065] opened 2024-12-15 13:07 UTC
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5556-chaos-lord-or-exalted-hero-with-chaos-chariot-or-gorbeast-chariot?page=1

**Comment by mfvreeland** [comment] 2024-12-19 19:47
Duplicate of #1883

**Closed by mfvreeland** 2024-12-19 19:47 UTC
Labels: unvalidated
