### ISSUE TITLE
Trappings of Blood set Bug

### ISSUE THREAD

**Issue by Aetius452** [chadvandy/cbfm_wh3#1916] opened 2024-07-09 21:23 UTC
I think the armour of Khorne for the warriors of chaos factions might be bugged since I never seem to get it unlike its paired Item, the axe of khorne. This keeps players from getting the set´s bonus.

**Comment by Aetius452** [comment] 2024-07-09 21:23
![20240709162230_1](https://github.com/chadvandy/cbfm_wh3/assets/175161225/8f68b488-7f34-438c-b320-da52eac35931)

**Comment by Drazhir2** [comment] 2024-07-10 06:27
Duplicate of #1917

**Closed by Drazhir2** 2024-07-10 06:27 UTC
Labels: unvalidated
