### ISSUE TITLE
Deceiver cannot move after sacking city (6.0.1 update) 

### ISSUE THREAD

**Issue by floskan** [chadvandy/cbfm_wh3#2089] opened 2024-12-17 21:00 UTC
https://community.creative-assembly.com/total-war/total-war-warhammer/bugs/5700-deceiver-cannot-move-after-sacking-city-6-0-1-update?page=1

**Comment by mfvreeland** [comment] 2024-12-19 22:17
Duplicate of #2026

**Closed by mfvreeland** 2024-12-19 22:17 UTC
Labels: duplicate
